name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check code formatting using gofmt
      uses: Jerome1337/gofmt-action@v1.0.4
