name: Update Docs

on:
  workflow_dispatch:

jobs:
  update-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18 

    - name: Install Protoc
      run: |
        sudo apt-get update -y
        sudo apt-get install -y protobuf-compiler

    - name: Install Protoc-gen-swagger
      run: |
        GO111MODULE=on go get github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2@latest
        sudo mv $(go env GOPATH)/bin/protoc-gen-openapiv2 $(go env GOPATH)/bin/protoc-gen-swagger

    - name: Download dependencies
      run: go mod download

    - name: Run make docs
      run: |
        make docs

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Update docs
        title: 'Update docs'
        body: 'Update docs'
        branch: 'docs-update-branch'
